openapi: 3.0.0
info:
  title: Aika API
  version: '1.2'
  description: Zoom会議支援サービス「aika」用API
servers:
  - url: 'http://localhost:3000'
paths:
  /api/meeting:
    post:
      summary: ミーティング作成
      tags:
        - meeting
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  ok:
                    type: boolean
                  code:
                    type: number
                  data:
                    type: object
                    required:
                      - agenda
                      - url
                      - id
                    properties:
                      url:
                        type: string
                        minLength: 1
                      id:
                        type: string
                        minLength: 1
                required:
                  - ok
                  - code
                  - data
              examples:
                例:
                  value:
                    ok: true
                    code: 200
                    data:
                      url: 'https://aika.lit-kansai-mentors.com/agenda/7e96e3956d65c49ed9dfec02b721e301'
                      id: 7e96e3956d65c49ed9dfec02b721e301
      operationId: post-api-meeting
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                start_time:
                  type: string
                  minLength: 1
                zoom_id:
                  type: string
                  minLength: 1
                zoom_pass:
                  type: string
                  minLength: 1
                agenda:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                        minLength: 1
                      duration:
                        type: number
                    required:
                      - title
                      - duration
              required:
                - title
                - start_time
                - zoom_id
                - zoom_pass
                - agenda
            examples:
              例:
                value:
                  title: taguchike meeting
                  start_time: '1605020400'
                  zoom_id: '5534291784'
                  zoom_pass: '3k0wsA'
                  agenda:
                    - title: 自己紹介
                      duration: 120
                    - title: 概要
                      duration: 300
  /api/meeting/:id/join:
    post:
      summary: AikaをZoomに招待
      tags:
        - meeting
      responses:
        '200':
          description: OK
        '500':
          description: Zoom接続エラー
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  ok:
                    type: boolean
                  code:
                    type: number
                  error:
                    type: string
                    minLength: 1
                required:
                  - ok
                  - code
                  - error
              examples:
                例:
                  value:
                    ok: false
                    code: 500
                    error: zoom connection error
      operationId: post-api-meeting-join
      description: idには、ミーティング作成時にサーバーから返されるIDを入れる
  /api/meeting/:id/start:
    post:
      summary: ミーティング開始
      tags:
        - meeting
      responses:
        '200':
          description: OK
      operationId: post-api-meeting-start
      description: idには、ミーティング作成時にサーバーから返されるIDを入れる
  /api/meeting/:id/finish:
    post:
      summary: ミーティング終了（Aika退出）
      tags:
        - meeting
      responses:
        '200':
          description: OK
      operationId: post-api-meeting-finish
      description: 'idには、ミーティング作成時にサーバーから返されるIDを入れる'
  /api/meeting/:id/mute_all:
    post:
      summary: 全員ミュート&アンミュート通知
      tags:
        - meeting
      responses:
        '200':
          description: OK
      operationId: post-api-meeting-mute_all
      description: 'idには、ミーティング作成時にサーバーから返されるIDを入れる'
  /api/meeting/:id/agenda/list.png:
    get:
      summary: アジェンダ画像取得
      tags:
        - meeting
      responses:
        '200':
            description: 'アジェンダ一覧の画像（1枚）'
      operationId: get-api-meeting-img
      description: 'idには、ミーティング作成時にサーバーから返されるIDを入れる。アジェンダ一覧の画像が返される。'
  /api/meeting/:id/ogp:
    get:
      summary: OGP画像取得
      tags:
        - meeting
      responses:
        '200':
            description: 'OGP画像（1枚）'
      operationId: get-api-ogp-img
      description: 'idには、ミーティング作成時にサーバーから返されるIDを入れる。OGP画像が返される。'
  /api/meeting/:id/agenda/next:
    post:
      summary: 議題変更
      tags:
        - agenda
      responses:
        '200':
          description: OK
      operationId: post-api-meeting-agenda-next
      description: 'idには、ミーティング作成時にサーバーから返されるIDを入れる'
components:
  schemas: {}
  securitySchemes: {}
